database/models/cliente.py
from peewee import Model, CharField, DateTimeField
from database.database import db
import datetime

class Cliente(Model):
    nome = CharField()
    email = CharField()
    data_registro = DateTimeField(default=datetime.datetime.now)

    class Meta:
        database = db

main.py
from flask import Flask
from configuration import configure_all

# inicializacao da API
app = Flask(__name__)

#configuracao da API
configure_all(app)

# execucao da API
app.run(debug=True)

routes/cliente.py
from flask import Blueprint,render_template, request
from database.models.cliente import Cliente

cliente_route = Blueprint('cliente', __name__)

@cliente_route.route('/')
def lista_clientes():
    """ Lista todos os clientes """

    #busca todos os clientes no banco de dados
    clientes = Cliente.select()

    return render_template('lista_clientes.html', clientes=clientes)

@cliente_route.route('/', methods=['POST'])
def inserir_cliente():
    """ Recebe os dados do cliente e insere no banco de dados """
    data = request.json

    novo_usuario = Cliente.create(
        nome=data['nome'], 
        email=data['email'],
    )

    return render_template('item_cliente.html', cliente=novo_usuario)


@cliente_route.route('/new')
def form_cliente():
    """ Renderiza o formulario de cadastro de cliente """
    return render_template('form_cliente.html')

@cliente_route.route('/<int:cliente_id>') 
#recebe o id do cliente como um parametro do tipo inteiro da rota e passa para o metodo detalhe_cliente
def detalhe_cliente(cliente_id):
    """ Obtem um cliente pelo id """

    #busca o cliente no db pelo id
    cliente = Cliente.get_by_id(cliente_id) 

    return render_template('detalhe_cliente.html', cliente=cliente)

@cliente_route.route('/<int:cliente_id>/edit') 
def form_edit_cliente(cliente_id):
    """ Renderiza o formulario de edicao de cliente """
    
    #busca o cliente no db pelo id
    cliente = Cliente.get_by_id(cliente_id)

    return render_template('form_cliente.html', cliente=cliente)


@cliente_route.route('/<int:cliente_id>/update', methods=['PUT']) 
def atualizar_cliente(cliente_id):
    """ Atualiza um cliente pelo id """
    # obtem os dados do formulario de edicao
    data = request.json

    cliente_editado = Cliente.get_by_id(cliente_id)

    #edita o cliente
    cliente_editado.nome = data['nome']
    cliente_editado.email = data['email']
    #salva as alteracoes
    cliente_editado.save()

    # editar usuario

    return render_template('item_cliente.html', cliente=cliente_editado)

@cliente_route.route('/<int:cliente_id>/delete', methods=['DELETE']) 
def deletar_cliente(cliente_id):
    """ Deletar um cliente pelo id """

    cliente = Cliente.get_by_id(cliente_id)
    cliente.delete_instance()
    return 'Cliente deletado com sucesso', 204

routes/home.py
from flask import Blueprint,render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

templates/detalhe_cliente.html
<ul>
    <li>Id: {{cliente.id}}</li>
    <li>Nome: {{cliente.nome}}</li>
    <li>E-mail: {{cliente.email}}</li>
</ul>

templates/form_cliente.html
<form class="c-form" 
    {% if cliente %}
        action="{{ url_for('cliente.atualizar_cliente', cliente_id = cliente.id) }}"
    {% else %}
        action="{{ url_for('cliente.inserir_cliente') }}"
    {% endif %}

    method="{% if cliente %}PUT{% else %}POST{% endif %}"

    {% if cliente %}
        c-swap="#cliente-{{ cliente.id }}"
    {% else %}
        c-prepend="#lista-clientes"
    {% endif %}

    c-reload-container="true">

    <div class="mb-3">
        <label class="form-label">Nome</label>
        <input 
            type="text" 
            class="form-control" 
            name="nome" {% if cliente %} 
            value="{{ cliente.nome }}" {% endif %}>
    </div>

    <div class="mb-3">
        <label class="form-label">Email</label>
        <input 
            type="email" 
            class="form-control" 
            name="email"
            {% if cliente %} value="{{ cliente.email }}" {% endif %}>
    </div>

    <button type="submit" class="btn btn-primary">
        {% if cliente %} Atualizar {% else %} Cadastrar {% endif %}
    </button>
</form>

templates/index.html
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Gestão de Clientes</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  </head>
  <body>
    <div class="container">

      <h1 class="text-center">Gestão de Clientes</h1>
    
      <!-- Formulário add Cliente -->
      <div id="form-cliente" 
      c-container="{{ url_for('cliente.form_cliente') }}"></div>

      <hr>
    
      <!-- Lista de Clientes -->
       <h2>Lista de clientes</h2>
      <div c-container="{{ url_for('cliente.lista_clientes') }}"></div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body" id="exibir-cliente">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
  </body>
</html>

templates/item_cliente.html
<tr id="cliente-{{ cliente.id }}">
    <th scope="row">{{ cliente.id }}</th>
    <td>{{ cliente.nome }}</td>
    <td>{{ cliente.email }}</td>
    <td>
        <button class="btn btn-secondary" 
        c-get="{{ url_for('cliente.detalhe_cliente', cliente_id = cliente.id) }}"
        c-target="#exibir-cliente"
        data-bs-toggle="modal"
        data-bs-target="#exampleModal">
            Ver
        </button>

        <button class="btn btn-primary" 
        c-get="{{ url_for('cliente.form_edit_cliente', cliente_id = cliente.id) }}"
        c-target="#form-cliente">
            Editar
        </button>

        <button class="btn btn-danger" 
            c-delete="{{ url_for('cliente.deletar_cliente', cliente_id = cliente.id) }}"
            c-remove-closest="tr"
            >Deletar</button>
    </td>
</tr>

templates/lista_clientes.html
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Email</th>
            <th scope="col">Ações</th>
        </tr>
    </thead>
    <tbody id="lista-clientes">

        {% for cliente in clientes %}
            {% include 'item_cliente.html' %}
        {% endfor %}

    </tbody>
</table>